http:
  port: 8080
admin:
  port: 9876
  host: 192.168.0.10
apiEndpoints:
  api:
    host: 192.168.0.10
    paths: "/ip"
  users:
    host: 192.168.0.10
    paths: ["/users", "/users/*"]
  transacciones:
    host: 192.168.0.10
    paths: ["/transacciones", "/transacciones/*"]
serviceEndpoints:
  httpbin:
    url: "https://httpbin.org"
  usersService:
    url: "http://192.168.0.10:3000"
  transaccionesService:
    url: "http://192.168.0.10:4000"
policies:
  - basic-auth
  - cors
  - expression
  - key-auth
  - log
  - oauth2
  - proxy
  - rate-limit
pipelines:
  default:
    apiEndpoints:
      - api
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: httpbin
              changeOrigin: true
  usersPipeline:
    apiEndpoints:
      - users
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: usersService
              changeOrigin: true
  transaccionesPipeline:
    apiEndpoints:
      - transacciones
    policies:
      # Uncomment `key-auth:` when instructed to in the Getting Started guide.
      # - key-auth:
      - proxy:
          - action:
              serviceEndpoint: transaccionesService
              changeOrigin: true
